language: go
go:
  - 1.7.x
  - master
  - tip
before_install:
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/Masterminds/glide
install:
  - glide install
script:
  - touch coverage.out
  - goveralls -coverprofile=coverage.out -service travis-ci
  - cat coverage.out
  - make test
